"""Serum 1 display tables -- AUTO-GENERATED by tools/gen_serum_tables.py.

Every list below was read back from the Serum 1 plugin itself (build of
Oct 2023, 96 filter types).  Indexed parameters are stored as
index / (count - 1); older builds have shorter lists but keep the same
order, and Serum re-bases the stored value when it loads them.
"""

# value = index / 95 (older builds: / 89, / 88)
FILTER_NAMES = [
    'MG Low 6',
    'MG Low 12',
    'MG Low 18',
    'MG Low 24',
    'Low 6',
    'Low 12',
    'Low 18',
    'Low 24',
    'High 6',
    'High 12',
    'High 18',
    'High 24',
    'Band 12',
    'Band 24',
    'Peak 12',
    'Peak 24',
    'Notch 12',
    'Notch 24',
    'LH 6',
    'LH 12',
    'LB 12',
    'LP 12',
    'LN 12',
    'HB 12',
    'HP 12',
    'HN 12',
    'BP 12',
    'BN 12',
    'PP 12',
    'PN 12',
    'NN 12',
    'L/B/H 12',
    'L/B/H 24',
    'L/P/H 12',
    'L/P/H 24',
    'L/N/H 12',
    'L/N/H 24',
    'B/P/N 12',
    'B/P/N 24',
    'Cmb +',
    'Cmb -',
    'Cmb L6+',
    'Cmb L6-',
    'Cmb H6+',
    'Cmb H6-',
    'Cmb HL6+',
    'Cmb HL6-',
    'Flg +',
    'Flg -',
    'Flg L6+',
    'Flg L6-',
    'Flg H6+',
    'Flg H6-',
    'Flg HL6+',
    'Flg HL6-',
    'Phs 12+',
    'Phs 12-',
    'Phs 24+',
    'Phs 24-',
    'Phs 36+',
    'Phs 36-',
    'Phs 48+',
    'Phs 48-',
    'Phs 48L6+',
    'Phs 48L6-',
    'Phs 48H6+',
    'Phs 48H6-',
    'Phs 48HL6+',
    'Phs 48HL6-',
    'FPhs 12HL6+',
    'FPhs 12HL6-',
    'Low EQ 6',
    'Low EQ 12',
    'Band EQ 12',
    'High EQ 6',
    'High EQ 12',
    'Ring Mod',
    'Ring Modx2',
    'SampHold',
    'SampHold-',
    'Combs',
    'Allpasses',
    'Reverb',
    'French LP',
    'German LP',
    'Add Bass',
    'Formant-I',
    'Formant-II',
    'Formant-III',
    'Bandreject',
    'Dist.Comb 1 LP',
    'Dist.Comb 1 BP',
    'Dist.Comb 2 LP',
    'Dist.Comb 2 BP',
    'Scream LP',
    'Scream BP',
]

# value = index / 23 (entry 18-20 read 'from A' on oscillator B)
WARP_NAMES = [
    'Off',
    'Sync',
    'Sync 1/2 Win.',
    'Sync Window',
    'Bend +',
    'Bend -',
    'Bend +/-',
    'PWM',
    'Asym +',
    'Asym -',
    'Asym +/-',
    'Flip',
    'Mirror',
    'Remap 1',
    'Remap 2',
    'Remap 3',
    'Remap 4',
    'Quantize',
    'FM (from B)',
    'AM (from B)',
    'RM (from B)',
    'FM (Noise)',
    'FM (Sub)',
    '',
]

# value = index / 15 (older builds with 13 modes: / 12)
DIST_MODE_NAMES = [
    'Tube',
    'SoftClip',
    'HardClip',
    'Diode 1',
    'Diode 2',
    'Lin.Fold',
    'Sin Fold',
    'Zero-Square',
    'Downsample',
    'Asym',
    'Rectify',
    'X-Shaper',
    'X-Shaper (Asym)',
    'Sine Shaper',
    'Stomp Box',
    'Tape Sat.',
]

# value = index / 8
UNISON_STACK_NAMES = [
    'off',
    '12 (1x)',
    '12 (2x)',
    '12 (3x)',
    '12+7(1x)',
    '12+7(2x)',
    '12+7(3x)',
    'Center-12',
    'Center-24',
]

# value = index / 4
SUB_SHAPE_NAMES = [
    'Sine',
    'RoundRect',
    'Saw',
    'Square',
    'Pulse',
]

# value = index / 2 (same for EQ TypH)
EQ_TYPE_NAMES = [
    'Shelf',
    'Peak',
    'LPF',
]

# value = index / 2
DELAY_MODE_NAMES = [
    'Normal',
    'Ping-Pong',
    'Tap->Delay',
]

# LFO rate knob, BPM mode: (first_step, last_step, division), 229 steps (value * 228)
LFO_BPM_RUNS = [
    (0, 13, '32 bar'),
    (14, 29, '16 bar'),
    (30, 46, '8 bar'),
    (47, 62, '4 bar'),
    (63, 78, '2 bar'),
    (79, 94, 'bar'),
    (95, 111, '1/2'),
    (112, 127, '1/4'),
    (128, 143, '1/8'),
    (144, 160, '1/16'),
    (161, 176, '1/32'),
    (177, 192, '1/64'),
    (193, 208, '1/128'),
    (209, 225, '1/256'),
    (226, 228, 'fast'),
]

# Delay time knob, synced: (first_step, last_step, division)
DELAY_SYNC_RUNS = [
    (0, 10, 'fast'),
    (11, 31, '1/256'),
    (32, 51, '1/128'),
    (52, 72, '1/64'),
    (73, 93, '1/32'),
    (94, 114, '1/16'),
    (115, 134, '1/8'),
    (135, 155, '1/4'),
    (156, 176, '1/2'),
    (177, 196, 'bar'),
    (197, 217, '2 bar'),
    (218, 228, '4 bar'),
]

# Compressor ratio knob: (first_step, last_step, text)
COMP_RATIO_RUNS = [
    (0, 0, '1:1'),
    (1, 5, '1.0:1'),
    (6, 17, '1.1:1'),
    (18, 28, '1.2:1'),
    (29, 39, '1.3:1'),
    (40, 51, '1.4:1'),
    (52, 62, '1.5:1'),
    (63, 74, '1.6:1'),
    (75, 85, '1.7:1'),
    (86, 96, '1.8:1'),
    (97, 108, '1.9:1'),
    (109, 151, '2:1'),
    (152, 170, '3:1'),
    (171, 182, '4:1'),
    (183, 190, '5:1'),
    (191, 195, '6:1'),
    (196, 199, '7:1'),
    (200, 205, '8:1'),
    (206, 208, '10:1'),
    (209, 214, '16:1'),
    (215, 223, '32:1'),
    (224, 228, 'Limit'),
]


# --- unit curves measured from the plugin's readouts -----------------------


def lfo_hz(n: float) -> float:
    """LFO rate knob in Hz mode: 0..100 Hz on a quartic curve."""
    return 100.0 * n ** 4


def fx_rate_hz(n: float) -> float:
    """Chorus/flanger/phaser rate knobs, unsynced: 0..20 Hz, quartic."""
    return 20.0 * n ** 4


def chaos_hz(n: float) -> float:
    """Chaos rate knob, unsynced: 0..1000 Hz, quintic."""
    return 1000.0 * n ** 5


def env_seconds(n: float) -> float:
    """Envelope attack/hold/decay/release: 0..32 s, quintic (0.5 -> 1.00 s)."""
    return 32.0 * n ** 5


def portamento_seconds(n: float) -> float:
    """Portamento time: 0..8 s, quintic."""
    return 8.0 * n ** 5


def cutoff_hz(n: float) -> float:
    """Filter cutoff knobs: 8 Hz .. 22050 Hz, log-linear."""
    return 8.0 * (22050.0 / 8.0) ** n


def log_hz(n: float, lo: float, hi: float) -> float:
    """Generic log-linear frequency knob (EQ, phaser centre, delay filter...)."""
    return lo * (hi / lo) ** n


def master_db(n: float) -> float:
    """Master volume: cubic amplitude, 100% = 0 dB, 70% = -9.3 dB."""
    import math
    return -200.0 if n <= 0.0 else 60.0 * math.log10(n)


def osc_level_amp(n: float) -> float:
    """Oscillator/sub/noise level knobs are quadratic in amplitude."""
    return n * n


def comp_ms(n: float) -> float:
    """Compressor attack/release: 0.1..1000 ms, quadratic."""
    return max(0.1, 1000.0 * n * n)


def delay_seconds(n: float) -> float:
    """Delay time knob, unsynced: 1 ms .. 501 ms as 1 + 500 n^4 (plugin read-out)."""
    return (1.0 + 500.0 * n ** 4) / 1000.0


def delay_offset(n: float) -> float:
    """Delay OFFSET knob: a 0.5x .. 1.5x multiplier of the time ("Dot 1/2" = 0.75, "Dot" = 1.5)."""
    return 0.5 + n


def lfo_division(step: int) -> str:
    """Division text for an LFO rate knob step (0..228) in BPM mode."""
    for a, b, text in LFO_BPM_RUNS:
        if a <= step <= b:
            return text
    return LFO_BPM_RUNS[-1][2]


def delay_division(step: int) -> str:
    for a, b, text in DELAY_SYNC_RUNS:
        if a <= step <= b:
            return text
    return DELAY_SYNC_RUNS[-1][2]


def indexed(value: float, counts: tuple[int, ...]) -> int | None:
    """Recover a menu index from a stored index/(count-1) value.

    `counts` lists the (count - 1) divisors to try, newest build first; the
    first one that lands on an integer wins.  Serum keeps the same order
    across builds and appends new entries, so the index is comparable.
    """
    for count in counts:
        scaled = value * count
        if abs(scaled - round(scaled)) < 0.02:
            return int(round(scaled))
    return None
