"""Generate serum2vital/serum_tables.py from tools/serum_display_tables.json.

The JSON is a dump of what the installed Serum 1 plugin displays for each
indexed parameter and for the LFO rate knob in both modes, captured by driving
the VST2 build headlessly (DawDreamer).  Regenerate with:

    python tools/gen_serum_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "serum_display_tables.json"
DST = ROOT / "serum2vital" / "serum_tables.py"


def runs(values):
    """Collapse a per-step list into (first_step, last_step, text) runs."""
    out = []
    for i, v in enumerate(values):
        if out and out[-1][2] == v:
            out[-1][1] = i
        else:
            out.append([i, i, v])
    return [tuple(r) for r in out]


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    enums = data["enums"]
    tables = data["tables"]

    lines = [
        '"""Serum 1 display tables -- AUTO-GENERATED by tools/gen_serum_tables.py.',
        "",
        "Every list below was read back from the Serum 1 plugin itself (build of",
        "Oct 2023, 96 filter types).  Indexed parameters are stored as",
        "index / (count - 1); older builds have shorter lists but keep the same",
        "order, and Serum re-bases the stored value when it loads them.",
        '"""',
        "",
    ]

    def emit_list(name, values, doc):
        lines.append(f"# {doc}")
        lines.append(f"{name} = [")
        for v in values:
            lines.append(f"    {v!r},")
        lines.append("]")
        lines.append("")

    emit_list("FILTER_NAMES", enums["Fil Type"], "value = index / 95 (older builds: / 89, / 88)")
    emit_list("WARP_NAMES", enums["WarpOscA"], "value = index / 23 (entry 18-20 read 'from A' on oscillator B)")
    emit_list("DIST_MODE_NAMES", enums["Dist_Mode"], "value = index / 15 (older builds with 13 modes: / 12)")
    emit_list("UNISON_STACK_NAMES", enums["A Uni Stack"], "value = index / 8")
    emit_list("SUB_SHAPE_NAMES", enums["SubOscShape"], "value = index / 4")
    emit_list("EQ_TYPE_NAMES", enums["EQ TypL"], "value = index / 2 (same for EQ TypH)")
    emit_list("DELAY_MODE_NAMES", enums["Dly_Mode"], "value = index / 2")

    lines.append("# LFO rate knob, BPM mode: (first_step, last_step, division), 229 steps (value * 228)")
    lines.append("LFO_BPM_RUNS = [")
    for a, b, t in runs(tables["LFO1 Rate [B0]"]):
        lines.append(f"    ({a}, {b}, {t!r}),")
    lines.append("]")
    lines.append("")
    lines.append("# Delay time knob, synced: (first_step, last_step, division)")
    lines.append("DELAY_SYNC_RUNS = [")
    for a, b, t in runs(enums["Dly_TimL"]):
        lines.append(f"    ({a}, {b}, {t!r}),")
    lines.append("]")
    lines.append("")
    lines.append("# Compressor ratio knob: (first_step, last_step, text)")
    lines.append("COMP_RATIO_RUNS = [")
    for a, b, t in runs(enums["Cmp_Rat"]):
        lines.append(f"    ({a}, {b}, {t!r}),")
    lines.append("]")
    lines.append("")
    lines.append(
        '''
# --- unit curves measured from the plugin's readouts -----------------------


def lfo_hz(n: float) -> float:
    """LFO rate knob in Hz mode: 0..100 Hz on a quartic curve."""
    return 100.0 * n ** 4


def fx_rate_hz(n: float) -> float:
    """Chorus/flanger/phaser rate knobs, unsynced: 0..20 Hz, quartic."""
    return 20.0 * n ** 4


def chaos_hz(n: float) -> float:
    """Chaos rate knob, unsynced: 0..1000 Hz, quintic."""
    return 1000.0 * n ** 5


def env_seconds(n: float) -> float:
    """Envelope attack/hold/decay/release: 0..32 s, quintic (0.5 -> 1.00 s)."""
    return 32.0 * n ** 5


def portamento_seconds(n: float) -> float:
    """Portamento time: 0..8 s, quintic."""
    return 8.0 * n ** 5


def cutoff_hz(n: float) -> float:
    """Filter cutoff knobs: 8 Hz .. 22050 Hz, log-linear."""
    return 8.0 * (22050.0 / 8.0) ** n


def log_hz(n: float, lo: float, hi: float) -> float:
    """Generic log-linear frequency knob (EQ, phaser centre, delay filter...)."""
    return lo * (hi / lo) ** n


def master_db(n: float) -> float:
    """Master volume: cubic amplitude, 100% = 0 dB, 70% = -9.3 dB."""
    import math
    return -200.0 if n <= 0.0 else 60.0 * math.log10(n)


def osc_level_amp(n: float) -> float:
    """Oscillator/sub/noise level knobs are quadratic in amplitude."""
    return n * n


def comp_ms(n: float) -> float:
    """Compressor attack/release: 0.1..1000 ms, quadratic."""
    return max(0.1, 1000.0 * n * n)


def lfo_division(step: int) -> str:
    """Division text for an LFO rate knob step (0..228) in BPM mode."""
    for a, b, text in LFO_BPM_RUNS:
        if a <= step <= b:
            return text
    return LFO_BPM_RUNS[-1][2]


def delay_division(step: int) -> str:
    for a, b, text in DELAY_SYNC_RUNS:
        if a <= step <= b:
            return text
    return DELAY_SYNC_RUNS[-1][2]


def indexed(value: float, counts: tuple[int, ...]) -> int | None:
    """Recover a menu index from a stored index/(count-1) value.

    `counts` lists the (count - 1) divisors to try, newest build first; the
    first one that lands on an integer wins.  Serum keeps the same order
    across builds and appends new entries, so the index is comparable.
    """
    for count in counts:
        scaled = value * count
        if abs(scaled - round(scaled)) < 0.02:
            return int(round(scaled))
    return None
'''.rstrip()
    )
    lines.append("")
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
